// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromptEngineering.Data;

#nullable disable

namespace PromptEngineering.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.ConversionInstance", b =>
                {
                    b.Property<int>("ConversionInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversionInstanceId"));

                    b.Property<string>("CodeSplitterJSON")
                        .HasColumnType("text");

                    b.Property<int>("ConversionStatus")
                        .HasColumnType("integer");

                    b.Property<int>("FileCollectionId")
                        .HasColumnType("integer");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<int?>("ResultFileCollectionId")
                        .HasColumnType("integer");

                    b.HasKey("ConversionInstanceId");

                    b.HasIndex("FileCollectionId");

                    b.ToTable("ConversionInstances");
                });

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.ConversionInstanceLog", b =>
                {
                    b.Property<int>("ConversionInstanceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversionInstanceLogId"));

                    b.Property<int>("ConversionInstanceId")
                        .HasColumnType("integer");

                    b.Property<string>("DetailedText")
                        .HasColumnType("text");

                    b.Property<int>("LogType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TitleText")
                        .HasColumnType("text");

                    b.HasKey("ConversionInstanceLogId");

                    b.HasIndex("ConversionInstanceId");

                    b.ToTable("ConversionInstanceLogs");
                });

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.DynamicPrompt", b =>
                {
                    b.Property<int>("DynamicPromptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DynamicPromptId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer");

                    b.Property<string>("SystemPromptKeysCommaSeperated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemPromptTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Temperature")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPromptKeysCommaSeperated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPromptTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DynamicPromptId");

                    b.ToTable("DynamicPrompts");
                });

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.FileCollection", b =>
                {
                    b.Property<int>("FileCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FileCollectionId"));

                    b.HasKey("FileCollectionId");

                    b.ToTable("FileCollections");
                });

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.FileEntry", b =>
                {
                    b.Property<int>("FileEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FileEntryId"));

                    b.Property<int>("FileCollectionId")
                        .HasColumnType("integer");

                    b.Property<string>("FileContent")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.HasKey("FileEntryId");

                    b.HasIndex("FileCollectionId");

                    b.ToTable("FileEntries");
                });

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.FileEntryMetadata", b =>
                {
                    b.Property<int>("FileEntryMetadataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FileEntryMetadataId"));

                    b.Property<int>("FileEntryId")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataJSON")
                        .HasColumnType("text");

                    b.HasKey("FileEntryMetadataId");

                    b.HasIndex("FileEntryId")
                        .IsUnique();

                    b.ToTable("FileEntryMetadatas");
                });

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.ConversionInstance", b =>
                {
                    b.HasOne("PromptEngineering.Data.ApplicationDBEntity.FileCollection", "FileCollection")
                        .WithMany()
                        .HasForeignKey("FileCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileCollection");
                });

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.ConversionInstanceLog", b =>
                {
                    b.HasOne("PromptEngineering.Data.ApplicationDBEntity.ConversionInstance", "ConversionInstance")
                        .WithMany("ConversionInstanceLogs")
                        .HasForeignKey("ConversionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversionInstance");
                });

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.FileEntry", b =>
                {
                    b.HasOne("PromptEngineering.Data.ApplicationDBEntity.FileCollection", "FileCollection")
                        .WithMany("FileEntries")
                        .HasForeignKey("FileCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileCollection");
                });

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.FileEntryMetadata", b =>
                {
                    b.HasOne("PromptEngineering.Data.ApplicationDBEntity.FileEntry", null)
                        .WithOne("FileEntryMetadata")
                        .HasForeignKey("PromptEngineering.Data.ApplicationDBEntity.FileEntryMetadata", "FileEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.ConversionInstance", b =>
                {
                    b.Navigation("ConversionInstanceLogs");
                });

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.FileCollection", b =>
                {
                    b.Navigation("FileEntries");
                });

            modelBuilder.Entity("PromptEngineering.Data.ApplicationDBEntity.FileEntry", b =>
                {
                    b.Navigation("FileEntryMetadata");
                });
#pragma warning restore 612, 618
        }
    }
}
